name: CI-CD

on:
  # Triggered on push and pull request events
  push:
  pull_request:
  # Allow manual runs
  workflow_dispatch:
  # Monthly runs on the 1st day of the month at midnight
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    env:
      # Access token for GitHub
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Preserve package sources for informative references in case of errors
      R_KEEP_PKG_SOURCE: yes
      # rsconnect is stricter than pak and would complain, see https://github.com/r-lib/pak/issues/485
      PKG_INCLUDE_LINKINGTO: true

    steps:

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::rsconnect

      - uses: r-lib/actions/check-r-package@v2

      - name: Deploy to shinyapps.io
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript deploy/deploy-shinyapps.R
