on: [push, pull_request]

name: CI-CD

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck,any::rsconnect

      - uses: r-lib/actions/check-r-package@v2

      - name: Deploy to shinyapps.io
        if: true || github.ref == 'refs/heads/master'
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          account_info <- lapply(paste0("SHINYAPPS_", c("ACCOUNT", "TOKEN", "SECRET")), Sys.getenv)
          do.call(rsconnect::setAccountInfo, account_info)
          app_files = c("app.R", "DESCRIPTION", "NAMESPACE", "R/", "inst/")
          rsconnect::deployApp(appName = "rTRhexNG-test", appFiles = app_files, forceUpdate = TRUE)
        shell: Rscript {0}

